name: neurosnake
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  built_collection: ^4.0.0
  built_value: ^6.1.4
  built_value_generator: ^6.1.4
  redux_epics: 0.10.2
  redux: ^3.0.0
  reselect: ^0.4.0
  rxdart: ^0.18.0
  meta: ^1.1.8
  less_dart: ^2.0.0
  sass_builder: ^2.0.0
  perceptron:
    path: '../perceptron'

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  source_gen: any
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
  webdev: any
